# Generated by Django 2.2.9 on 2020-03-08 07:55

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='test_user', max_length=200)),
                ('game', models.CharField(default=uuid.UUID('3a4e790c-6112-11ea-a9f8-94e6f70741de'), max_length=200)),
                ('start_contributor', models.CharField(max_length=200)),
                ('end_contributor', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(null=True, verbose_name='game start time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='game end time')),
                ('shortest_path', models.IntegerField()),
                ('is_solved', models.BooleanField(default=False)),
                ('moves', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
            ],
        ),
    ]
