# Generated by Django 5.1.1 on 2025-07-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='test_user', max_length=200)),
                ('start_contributor', models.CharField(max_length=200)),
                ('end_contributor', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(null=True, verbose_name='game start time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='game end time')),
                ('shortest_path', models.IntegerField()),
                ('is_solved', models.BooleanField(default=False)),
                ('moves_json', models.TextField(blank=True, default='{}', null=True)),
            ],
        ),
    ]
