[tool.poetry]
name = "cinema"
version = "0.2.1"
description = "Game of the cinema graph"
authors = ["Chivon Powers <chivon.powers@gmail.com>", "Reuben Brasher <rkbrasher@gmail.com>"]
license = "mit"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.18"
pandas = "^1.2"
networkx = "^3.2"
cinemagoer = "^2023.5.1"
Django = "^5.0"
djangorestframework = "^3.14"
django-extensions = "^3.2"
gensim = "^4.3"
tqdm = "^4.56"
requests = "^2.31"
black = "^24.2.0"
ruff = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
